//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QrCodeGenerator.Properties;

using System.Globalization;
using System.Resources;

public static class Resources
{
    private static readonly ResourceManager ResourceManager =
        new("QrCodeGenerator.Properties.Resources", typeof(Resources).Assembly);

    public static string WindowTitle => GetString(nameof(WindowTitle));
    public static string AppTitle => GetString(nameof(AppTitle));
    public static string AppSubtitle => GetString(nameof(AppSubtitle));
    public static string InputLabel => GetString(nameof(InputLabel));
    public static string InputPlaceholder => GetString(nameof(InputPlaceholder));
    public static string StatusGeneratingOnInput => GetString(nameof(StatusGeneratingOnInput));
    public static string StatusReady => GetString(nameof(StatusReady));
    public static string StatusSaved => GetString(nameof(StatusSaved));
    public static string StatusSaveFailed => GetString(nameof(StatusSaveFailed));
    public static string StatusGenerationFailed => GetString(nameof(StatusGenerationFailed));
    public static string StatusDataTooLong => GetString(nameof(StatusDataTooLong));
    public static string PlaceholderTitle => GetString(nameof(PlaceholderTitle));
    public static string PlaceholderSubtitle => GetString(nameof(PlaceholderSubtitle));
    public static string LoadingText => GetString(nameof(LoadingText));
    public static string GenerateButton => GetString(nameof(GenerateButton));
    public static string SaveButton => GetString(nameof(SaveButton));
    public static string ClearButton => GetString(nameof(ClearButton));
    public static string SaveDialogTitle => GetString(nameof(SaveDialogTitle));
    public static string SaveDialogFilter => GetString(nameof(SaveDialogFilter));
    public static string ErrorTitle => GetString(nameof(ErrorTitle));
    public static string ErrorGenerationMessage => GetString(nameof(ErrorGenerationMessage));
    public static string ErrorSaveMessage => GetString(nameof(ErrorSaveMessage));
    public static string CharacterCountOne => GetString(nameof(CharacterCountOne));
    public static string CharacterCountFew => GetString(nameof(CharacterCountFew));
    public static string CharacterCountMany => GetString(nameof(CharacterCountMany));
    public static string AutomationInputTextBox => GetString(nameof(AutomationInputTextBox));
    public static string AutomationGenerateButton => GetString(nameof(AutomationGenerateButton));
    public static string AutomationSaveButton => GetString(nameof(AutomationSaveButton));
    public static string AutomationClearButton => GetString(nameof(AutomationClearButton));
    public static string AutomationQrPreview => GetString(nameof(AutomationQrPreview));
    public static string LanguageLabel => GetString(nameof(LanguageLabel));
    public static string AutomationLanguageSelector => GetString(nameof(AutomationLanguageSelector));
    public static string InstallLabel => GetString(nameof(InstallLabel));
    public static string InstallButton => GetString(nameof(InstallButton));
    public static string InstallDialogTitle => GetString(nameof(InstallDialogTitle));
    public static string InstallDialogDescription => GetString(nameof(InstallDialogDescription));
    public static string InstallOptionLocalTitle => GetString(nameof(InstallOptionLocalTitle));
    public static string InstallOptionLocalDescription => GetString(nameof(InstallOptionLocalDescription));
    public static string InstallOptionRoamingTitle => GetString(nameof(InstallOptionRoamingTitle));
    public static string InstallOptionRoamingDescription => GetString(nameof(InstallOptionRoamingDescription));
    public static string InstallOptionAllUsersTitle => GetString(nameof(InstallOptionAllUsersTitle));
    public static string InstallOptionAllUsersDescription => GetString(nameof(InstallOptionAllUsersDescription));
    public static string InstallDialogConfirm => GetString(nameof(InstallDialogConfirm));
    public static string InstallDialogCancel => GetString(nameof(InstallDialogCancel));
    public static string InstallSuccessTitle => GetString(nameof(InstallSuccessTitle));
    public static string InstallSuccessMessage => GetString(nameof(InstallSuccessMessage));
    public static string InstallSuccessWithWarningMessage => GetString(nameof(InstallSuccessWithWarningMessage));
    public static string InstallShortcutWarning => GetString(nameof(InstallShortcutWarning));
    public static string InstallFailedTitle => GetString(nameof(InstallFailedTitle));
    public static string InstallFailedMessage => GetString(nameof(InstallFailedMessage));
    public static string AutomationInstallButton => GetString(nameof(AutomationInstallButton));

    private static string GetString(string name) =>
        ResourceManager.GetString(name, CultureInfo.CurrentUICulture) ?? name;
}