#!/usr/bin/env python3
"""Generate satellite .resx files for QrCodeGenerator localization."""

from pathlib import Path
import xml.etree.ElementTree as ET

PROPS_DIR = Path(__file__).resolve().parent.parent / "Properties"

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""

TRANSLATIONS = {
    "en": {
        "WindowTitle": "QR Code Generator",
        "AppTitle": "QR Code Generator",
        "AppSubtitle": "Create QR codes from text and links",
        "InputLabel": "Text or link",
        "InputPlaceholder": "Enter text or URL to generate a QR code",
        "StatusGeneratingOnInput": "Generating as you type...",
        "StatusReady": "QR code is ready. You can save it as PNG.",
        "StatusSaved": "Saved: {0}",
        "StatusSaveFailed": "Failed to save file",
        "StatusGenerationFailed": "Generation error",
        "StatusDataTooLong": "Text is too long for a QR code. Shorten your input.",
        "PlaceholderTitle": "Your QR code will appear here",
        "PlaceholderSubtitle": "Start typing on the left",
        "LoadingText": "Generating...",
        "GenerateButton": "Generate",
        "SaveButton": "Save PNG",
        "ClearButton": "Clear",
        "SaveDialogTitle": "Save QR code",
        "SaveDialogFilter": "PNG image (*.png)|*.png",
        "ErrorTitle": "Error",
        "ErrorGenerationMessage": "Failed to create QR code:\n{0}",
        "ErrorSaveMessage": "Failed to save file:\n{0}",
        "CharacterCountOne": "character",
        "CharacterCountFew": "characters",
        "CharacterCountMany": "characters",
        "LanguageLabel": "Language",
        "AutomationInputTextBox": "Text or link input field",
        "AutomationGenerateButton": "Generate QR code",
        "AutomationSaveButton": "Save QR code as PNG",
        "AutomationClearButton": "Clear input and preview",
        "AutomationQrPreview": "QR code preview",
        "AutomationLanguageSelector": "Language selector",
    },
    "de": {
        "WindowTitle": "QR-Code-Generator",
        "AppTitle": "QR-Code-Generator",
        "AppSubtitle": "Erstellen Sie QR-Codes aus Text und Links",
        "InputLabel": "Text oder Link",
        "InputPlaceholder": "Text oder URL eingeben, um einen QR-Code zu erstellen",
        "StatusGeneratingOnInput": "Generierung bei Eingabe...",
        "StatusReady": "QR-Code ist fertig. Als PNG speichern.",
        "StatusSaved": "Gespeichert: {0}",
        "StatusSaveFailed": "Datei konnte nicht gespeichert werden",
        "StatusGenerationFailed": "Generierungsfehler",
        "StatusDataTooLong": "Text ist zu lang für einen QR-Code. Kürzen Sie die Eingabe.",
        "PlaceholderTitle": "Hier erscheint der QR-Code",
        "PlaceholderSubtitle": "Beginnen Sie links mit der Eingabe",
        "LoadingText": "Generierung...",
        "GenerateButton": "Generieren",
        "SaveButton": "PNG speichern",
        "ClearButton": "Löschen",
        "SaveDialogTitle": "QR-Code speichern",
        "SaveDialogFilter": "PNG-Bild (*.png)|*.png",
        "ErrorTitle": "Fehler",
        "ErrorGenerationMessage": "QR-Code konnte nicht erstellt werden:\n{0}",
        "ErrorSaveMessage": "Datei konnte nicht gespeichert werden:\n{0}",
        "CharacterCountOne": "Zeichen",
        "CharacterCountFew": "Zeichen",
        "CharacterCountMany": "Zeichen",
        "LanguageLabel": "Sprache",
        "AutomationInputTextBox": "Eingabefeld für Text oder Link",
        "AutomationGenerateButton": "QR-Code generieren",
        "AutomationSaveButton": "QR-Code als PNG speichern",
        "AutomationClearButton": "Eingabe und Vorschau löschen",
        "AutomationQrPreview": "QR-Code-Vorschau",
        "AutomationLanguageSelector": "Sprachauswahl",
    },
    "ru": {
        "WindowTitle": "QR Code Generator",
        "AppTitle": "QR Code Generator",
        "AppSubtitle": "Создавайте QR-коды из текста и ссылок",
        "InputLabel": "Текст или ссылка",
        "InputPlaceholder": "Введите текст или URL для генерации QR-кода",
        "StatusGeneratingOnInput": "Генерация при вводе...",
        "StatusReady": "QR-код готов. Можно сохранить как PNG.",
        "StatusSaved": "Сохранено: {0}",
        "StatusSaveFailed": "Не удалось сохранить файл",
        "StatusGenerationFailed": "Ошибка генерации",
        "StatusDataTooLong": "Текст слишком длинный для QR-кода. Сократите ввод.",
        "PlaceholderTitle": "Здесь появится QR-код",
        "PlaceholderSubtitle": "Начните вводить текст слева",
        "LoadingText": "Генерация...",
        "GenerateButton": "Сгенерировать",
        "SaveButton": "Сохранить PNG",
        "ClearButton": "Очистить",
        "SaveDialogTitle": "Сохранить QR-код",
        "SaveDialogFilter": "PNG изображение (*.png)|*.png",
        "ErrorTitle": "Ошибка",
        "ErrorGenerationMessage": "Не удалось создать QR-код:\n{0}",
        "ErrorSaveMessage": "Не удалось сохранить файл:\n{0}",
        "CharacterCountOne": "символ",
        "CharacterCountFew": "символа",
        "CharacterCountMany": "символов",
        "LanguageLabel": "Язык",
        "AutomationInputTextBox": "Поле ввода текста или ссылки",
        "AutomationGenerateButton": "Сгенерировать QR-код",
        "AutomationSaveButton": "Сохранить QR-код как PNG",
        "AutomationClearButton": "Очистить ввод и предпросмотр",
        "AutomationQrPreview": "Предпросмотр QR-кода",
        "AutomationLanguageSelector": "Выбор языка",
    },
    "uk": {
        "WindowTitle": "Генератор QR-кодів",
        "AppTitle": "Генератор QR-кодів",
        "AppSubtitle": "Створюйте QR-коди з тексту та посилань",
        "InputLabel": "Текст або посилання",
        "InputPlaceholder": "Введіть текст або URL для генерації QR-коду",
        "StatusGeneratingOnInput": "Генерація під час введення...",
        "StatusReady": "QR-код готовий. Можна зберегти як PNG.",
        "StatusSaved": "Збережено: {0}",
        "StatusSaveFailed": "Не вдалося зберегти файл",
        "StatusGenerationFailed": "Помилка генерації",
        "StatusDataTooLong": "Текст занадто довгий для QR-коду. Скоротіть введення.",
        "PlaceholderTitle": "Тут з'явиться QR-код",
        "PlaceholderSubtitle": "Почніть вводити текст зліва",
        "LoadingText": "Генерація...",
        "GenerateButton": "Згенерувати",
        "SaveButton": "Зберегти PNG",
        "ClearButton": "Очистити",
        "SaveDialogTitle": "Зберегти QR-код",
        "SaveDialogFilter": "PNG зображення (*.png)|*.png",
        "ErrorTitle": "Помилка",
        "ErrorGenerationMessage": "Не вдалося створити QR-код:\n{0}",
        "ErrorSaveMessage": "Не вдалося зберегти файл:\n{0}",
        "CharacterCountOne": "символ",
        "CharacterCountFew": "символи",
        "CharacterCountMany": "символів",
        "LanguageLabel": "Мова",
        "AutomationInputTextBox": "Поле введення тексту або посилання",
        "AutomationGenerateButton": "Згенерувати QR-код",
        "AutomationSaveButton": "Зберегти QR-код як PNG",
        "AutomationClearButton": "Очистити введення та попередній перегляд",
        "AutomationQrPreview": "Попередній перегляд QR-коду",
        "AutomationLanguageSelector": "Вибір мови",
    },
    "be": {
        "WindowTitle": "Генератар QR-кодаў",
        "AppTitle": "Генератар QR-кодаў",
        "AppSubtitle": "Стварайце QR-коды з тэксту і спасылак",
        "InputLabel": "Тэкст або спасылка",
        "InputPlaceholder": "Увядзіце тэкст або URL для генерацыі QR-кода",
        "StatusGeneratingOnInput": "Генерацыя пры ўводзе...",
        "StatusReady": "QR-код гатовы. Можна захаваць як PNG.",
        "StatusSaved": "Захавана: {0}",
        "StatusSaveFailed": "Не ўдалося захаваць файл",
        "StatusGenerationFailed": "Памылка генерацыі",
        "StatusDataTooLong": "Тэкст занадта доўгі для QR-кода. Скараціце ўвод.",
        "PlaceholderTitle": "Тут з'явіцца QR-код",
        "PlaceholderSubtitle": "Пачніце ўводзіць тэкст злева",
        "LoadingText": "Генерацыя...",
        "GenerateButton": "Згенераваць",
        "SaveButton": "Захаваць PNG",
        "ClearButton": "Ачысціць",
        "SaveDialogTitle": "Захаваць QR-код",
        "SaveDialogFilter": "PNG выява (*.png)|*.png",
        "ErrorTitle": "Памылка",
        "ErrorGenerationMessage": "Не ўдалося стварыць QR-код:\n{0}",
        "ErrorSaveMessage": "Не ўдалося захаваць файл:\n{0}",
        "CharacterCountOne": "сімвал",
        "CharacterCountFew": "сімвалы",
        "CharacterCountMany": "сімвалаў",
        "LanguageLabel": "Мова",
        "AutomationInputTextBox": "Поле ўводу тэксту або спасылкі",
        "AutomationGenerateButton": "Згенераваць QR-код",
        "AutomationSaveButton": "Захаваць QR-код як PNG",
        "AutomationClearButton": "Ачысціць увод і папярэдні прагляд",
        "AutomationQrPreview": "Папярэдні прагляд QR-кода",
        "AutomationLanguageSelector": "Выбар мовы",
    },
    "kk": {
        "WindowTitle": "QR код генераторы",
        "AppTitle": "QR код генераторы",
        "AppSubtitle": "Мәтін мен сілтемелерден QR кодтар жасаңыз",
        "InputLabel": "Мәтін немесе сілтеме",
        "InputPlaceholder": "QR код жасау үшін мәтін немесе URL енгізіңіз",
        "StatusGeneratingOnInput": "Енгізу кезінде генерация...",
        "StatusReady": "QR код дайын. PNG ретінде сақтауға болады.",
        "StatusSaved": "Сақталды: {0}",
        "StatusSaveFailed": "Файлды сақтау мүмкін болмады",
        "StatusGenerationFailed": "Генерация қатесі",
        "StatusDataTooLong": "Мәтін QR код үшін тым ұзын. Енгізуді қысқартыңыз.",
        "PlaceholderTitle": "QR код осында пайда болады",
        "PlaceholderSubtitle": "Сол жақта мәтін енгізуді бастаңыз",
        "LoadingText": "Генерация...",
        "GenerateButton": "Жасау",
        "SaveButton": "PNG сақтау",
        "ClearButton": "Тазалау",
        "SaveDialogTitle": "QR кодты сақтау",
        "SaveDialogFilter": "PNG сурет (*.png)|*.png",
        "ErrorTitle": "Қате",
        "ErrorGenerationMessage": "QR код жасау мүмкін болмады:\n{0}",
        "ErrorSaveMessage": "Файлды сақтау мүмкін болмады:\n{0}",
        "CharacterCountOne": "таңба",
        "CharacterCountFew": "таңба",
        "CharacterCountMany": "таңба",
        "LanguageLabel": "Тіл",
        "AutomationInputTextBox": "Мәтін немесе сілтеме енгізу өрісі",
        "AutomationGenerateButton": "QR код жасау",
        "AutomationSaveButton": "QR кодты PNG ретінде сақтау",
        "AutomationClearButton": "Енгізуді және алдын ала қарауды тазалау",
        "AutomationQrPreview": "QR код алдын ала қарауы",
        "AutomationLanguageSelector": "Тіл таңдау",
    },
    "uz": {
        "WindowTitle": "QR kod generatori",
        "AppTitle": "QR kod generatori",
        "AppSubtitle": "Matn va havolalardan QR kodlar yarating",
        "InputLabel": "Matn yoki havola",
        "InputPlaceholder": "QR kod yaratish uchun matn yoki URL kiriting",
        "StatusGeneratingOnInput": "Yozishda generatsiya...",
        "StatusReady": "QR kod tayyor. PNG sifatida saqlash mumkin.",
        "StatusSaved": "Saqlandi: {0}",
        "StatusSaveFailed": "Faylni saqlab bo'lmadi",
        "StatusGenerationFailed": "Generatsiya xatosi",
        "StatusDataTooLong": "Matn QR kod uchun juda uzun. Kiritishni qisqartiring.",
        "PlaceholderTitle": "QR kod shu yerda paydo bo'ladi",
        "PlaceholderSubtitle": "Chap tomonda matn kiritishni boshlang",
        "LoadingText": "Generatsiya...",
        "GenerateButton": "Yaratish",
        "SaveButton": "PNG saqlash",
        "ClearButton": "Tozalash",
        "SaveDialogTitle": "QR kodni saqlash",
        "SaveDialogFilter": "PNG rasm (*.png)|*.png",
        "ErrorTitle": "Xato",
        "ErrorGenerationMessage": "QR kod yaratib bo'lmadi:\n{0}",
        "ErrorSaveMessage": "Faylni saqlab bo'lmadi:\n{0}",
        "CharacterCountOne": "belgi",
        "CharacterCountFew": "belgi",
        "CharacterCountMany": "belgi",
        "LanguageLabel": "Til",
        "AutomationInputTextBox": "Matn yoki havola kiritish maydoni",
        "AutomationGenerateButton": "QR kod yaratish",
        "AutomationSaveButton": "QR kodni PNG sifatida saqlash",
        "AutomationClearButton": "Kiritish va oldindan ko'rishni tozalash",
        "AutomationQrPreview": "QR kod oldindan ko'rinishi",
        "AutomationLanguageSelector": "Til tanlash",
    },
    "hy": {
        "WindowTitle": "QR կոդի գեներատոր",
        "AppTitle": "QR կոդի գեներատոր",
        "AppSubtitle": "Ստեղծեք QR կոդեր տեքստից և հղումներից",
        "InputLabel": "Տեքստ կամ հղում",
        "InputPlaceholder": "Մուտքագրեք տեքստ կամ URL QR կոդ ստեղծելու համար",
        "StatusGeneratingOnInput": "Գեներացիա մուտքագրման ժամանակ...",
        "StatusReady": "QR կոդը պատրաստ է։ Կարող եք պահել PNG ձևաչափով։",
        "StatusSaved": "Պահված է՝ {0}",
        "StatusSaveFailed": "Չհաջողվեց պահել ֆայլը",
        "StatusGenerationFailed": "Գեներացիայի սխալ",
        "StatusDataTooLong": "Տեքստը չափազանց երկար է QR կոդի համար։ Կրճատեք մուտքագրումը։",
        "PlaceholderTitle": "QR կոդը կհայտնվի այստեղ",
        "PlaceholderSubtitle": "Սկսեք մուտքագրել տեքստը ձախ կողմում",
        "LoadingText": "Գեներացիա...",
        "GenerateButton": "Ստեղծել",
        "SaveButton": "Պահել PNG",
        "ClearButton": "Մաքրել",
        "SaveDialogTitle": "Պահել QR կոդը",
        "SaveDialogFilter": "PNG պատկեր (*.png)|*.png",
        "ErrorTitle": "Սխալ",
        "ErrorGenerationMessage": "Չհաջողվեց ստեղծել QR կոդը:\n{0}",
        "ErrorSaveMessage": "Չհաջողվեց պահել ֆայլը:\n{0}",
        "CharacterCountOne": "նիշ",
        "CharacterCountFew": "նիշ",
        "CharacterCountMany": "նիշ",
        "LanguageLabel": "Լեզու",
        "AutomationInputTextBox": "Տեքստի կամ հղման մուտքագրման դաշտ",
        "AutomationGenerateButton": "Ստեղծել QR կոդ",
        "AutomationSaveButton": "Պահել QR կոդը PNG ձևաչափով",
        "AutomationClearButton": "Մաքրել մուտքագրումը և նախադիտումը",
        "AutomationQrPreview": "QR կոդի նախադիտում",
        "AutomationLanguageSelector": "Լեզվի ընտրություն",
    },
    "az": {
        "WindowTitle": "QR kod generatoru",
        "AppTitle": "QR kod generatoru",
        "AppSubtitle": "Mətn və keçidlərdən QR kodlar yaradın",
        "InputLabel": "Mətn və ya keçid",
        "InputPlaceholder": "QR kod yaratmaq üçün mətn və ya URL daxil edin",
        "StatusGeneratingOnInput": "Yazarkən generasiya...",
        "StatusReady": "QR kod hazırdır. PNG kimi saxlamaq olar.",
        "StatusSaved": "Saxlanıldı: {0}",
        "StatusSaveFailed": "Fayl saxlanıla bilmədi",
        "StatusGenerationFailed": "Generasiya xətası",
        "StatusDataTooLong": "Mətn QR kod üçün çox uzundur. Daxiletməni qısaldın.",
        "PlaceholderTitle": "QR kod burada görünəcək",
        "PlaceholderSubtitle": "Solda mətn daxil etməyə başlayın",
        "LoadingText": "Generasiya...",
        "GenerateButton": "Yarat",
        "SaveButton": "PNG saxla",
        "ClearButton": "Təmizlə",
        "SaveDialogTitle": "QR kodu saxla",
        "SaveDialogFilter": "PNG şəkil (*.png)|*.png",
        "ErrorTitle": "Xəta",
        "ErrorGenerationMessage": "QR kod yaradıla bilmədi:\n{0}",
        "ErrorSaveMessage": "Fayl saxlanıla bilmədi:\n{0}",
        "CharacterCountOne": "simvol",
        "CharacterCountFew": "simvol",
        "CharacterCountMany": "simvol",
        "LanguageLabel": "Dil",
        "AutomationInputTextBox": "Mətn və ya keçid daxiletmə sahəsi",
        "AutomationGenerateButton": "QR kod yarat",
        "AutomationSaveButton": "QR kodu PNG kimi saxla",
        "AutomationClearButton": "Daxiletməni və önizləməni təmizlə",
        "AutomationQrPreview": "QR kod önizləməsi",
        "AutomationLanguageSelector": "Dil seçimi",
    },
    "ka": {
        "WindowTitle": "QR კოდის გენერატორი",
        "AppTitle": "QR კოდის გენერატორი",
        "AppSubtitle": "შექმენით QR კოდები ტექსტიდან და ბმულებიდან",
        "InputLabel": "ტექსტი ან ბმული",
        "InputPlaceholder": "შეიყვანეთ ტექსტი ან URL QR კოდის შესაქმნელად",
        "StatusGeneratingOnInput": "გენერაცია შეყვანისას...",
        "StatusReady": "QR კოდი მზადაა. შეგიძლიათ PNG-ად შეინახოთ.",
        "StatusSaved": "შენახულია: {0}",
        "StatusSaveFailed": "ფაილის შენახვა ვერ მოხერხდა",
        "StatusGenerationFailed": "გენერაციის შეცდომა",
        "StatusDataTooLong": "ტექსტი ძალიან გრძელია QR კოდისთვის. შეამცირეთ შეყვანა.",
        "PlaceholderTitle": "QR კოდი აქ გამოჩნდება",
        "PlaceholderSubtitle": "დაიწყეთ ტექსტის შეყვანა მარცხნივ",
        "LoadingText": "გენერაცია...",
        "GenerateButton": "შექმნა",
        "SaveButton": "PNG შენახვა",
        "ClearButton": "გასუფთავება",
        "SaveDialogTitle": "QR კოდის შენახვა",
        "SaveDialogFilter": "PNG სურათი (*.png)|*.png",
        "ErrorTitle": "შეცდომა",
        "ErrorGenerationMessage": "QR კოდის შექმნა ვერ მოხერხდა:\n{0}",
        "ErrorSaveMessage": "ფაილის შენახვა ვერ მოხერხდა:\n{0}",
        "CharacterCountOne": "სიმბოლო",
        "CharacterCountFew": "სიმბოლო",
        "CharacterCountMany": "სიმბოლო",
        "LanguageLabel": "ენა",
        "AutomationInputTextBox": "ტექსტის ან ბმულის შეყვანის ველი",
        "AutomationGenerateButton": "QR კოდის შექმნა",
        "AutomationSaveButton": "QR კოდის PNG-ად შენახვა",
        "AutomationClearButton": "შეყვანისა და გადახედვის გასუფთავება",
        "AutomationQrPreview": "QR კოდის გადახედვა",
        "AutomationLanguageSelector": "ენის არჩევა",
    },
    "ky": {
        "WindowTitle": "QR код генератору",
        "AppTitle": "QR код генератору",
        "AppSubtitle": "Текст жана шилтемелерден QR коддорду түзүңүз",
        "InputLabel": "Текст же шилтеме",
        "InputPlaceholder": "QR код түзүү үчүн текст же URL киргизиңиз",
        "StatusGeneratingOnInput": "Киргизүү учурунда генерация...",
        "StatusReady": "QR код даяр. PNG катары сактоого болот.",
        "StatusSaved": "Сакталды: {0}",
        "StatusSaveFailed": "Файл сакталган жок",
        "StatusGenerationFailed": "Генерация катасы",
        "StatusDataTooLong": "Текст QR код үчүн өтө узун. Киргизүүнү кыскартыңыз.",
        "PlaceholderTitle": "QR код бул жерде пайда болот",
        "PlaceholderSubtitle": "Сол жакта текст киргизүүнү баштаңыз",
        "LoadingText": "Генерация...",
        "GenerateButton": "Түзүү",
        "SaveButton": "PNG сактоо",
        "ClearButton": "Тазалоо",
        "SaveDialogTitle": "QR кодду сактоо",
        "SaveDialogFilter": "PNG сүрөт (*.png)|*.png",
        "ErrorTitle": "Ката",
        "ErrorGenerationMessage": "QR код түзүлбөй калды:\n{0}",
        "ErrorSaveMessage": "Файл сакталган жок:\n{0}",
        "CharacterCountOne": "белги",
        "CharacterCountFew": "белги",
        "CharacterCountMany": "белги",
        "LanguageLabel": "Тил",
        "AutomationInputTextBox": "Текст же шилтеме киргизүү талаасы",
        "AutomationGenerateButton": "QR код түзүү",
        "AutomationSaveButton": "QR кодду PNG катары сактоо",
        "AutomationClearButton": "Киргизүүнү жана алдын ала көрүүнү тазалоо",
        "AutomationQrPreview": "QR коддун алдын ала көрүнүшү",
        "AutomationLanguageSelector": "Тил тандоо",
    },
    "tg": {
        "WindowTitle": "Генератори QR-код",
        "AppTitle": "Генератори QR-код",
        "AppSubtitle": "Аз матн ва пайвандҳо QR-код эҷод кунед",
        "InputLabel": "Матн ё пайванд",
        "InputPlaceholder": "Барои эҷоди QR-код матн ё URL ворид кунед",
        "StatusGeneratingOnInput": "Ҳангоми воридкунӣ эҷод мешавад...",
        "StatusReady": "QR-код омода аст. Метавонед ҳамчун PNG нигоҳ доред.",
        "StatusSaved": "Нигоҳ дошта шуд: {0}",
        "StatusSaveFailed": "Файл нигоҳ дошта нашуд",
        "StatusGenerationFailed": "Хатогии эҷод",
        "StatusDataTooLong": "Матн барои QR-код хеле дароз аст. Воридотро кӯтоҳ кунед.",
        "PlaceholderTitle": "QR-код дар ин ҷо пайдо мешавад",
        "PlaceholderSubtitle": "Аз чап матн ворид карданро оғоз кунед",
        "LoadingText": "Эҷод...",
        "GenerateButton": "Эҷод кардан",
        "SaveButton": "Нигоҳ доштани PNG",
        "ClearButton": "Тоза кардан",
        "SaveDialogTitle": "Нигоҳ доштани QR-код",
        "SaveDialogFilter": "Тасвири PNG (*.png)|*.png",
        "ErrorTitle": "Хатогӣ",
        "ErrorGenerationMessage": "QR-код эҷод нашуд:\n{0}",
        "ErrorSaveMessage": "Файл нигоҳ дошта нашуд:\n{0}",
        "CharacterCountOne": "аломат",
        "CharacterCountFew": "аломат",
        "CharacterCountMany": "аломат",
        "LanguageLabel": "Забон",
        "AutomationInputTextBox": "Майдони воридоти матн ё пайванд",
        "AutomationGenerateButton": "Эҷоди QR-код",
        "AutomationSaveButton": "Нигоҳ доштани QR-код ҳамчун PNG",
        "AutomationClearButton": "Тоза кардани воридот ва пешнамоиш",
        "AutomationQrPreview": "Пешнамоиши QR-код",
        "AutomationLanguageSelector": "Интихоби забон",
    },
    "tk": {
        "WindowTitle": "QR kod generator",
        "AppTitle": "QR kod generator",
        "AppSubtitle": "Tekst we baglanyşyklardan QR kodlar dörediň",
        "InputLabel": "Tekst ýa-da baglanyşyk",
        "InputPlaceholder": "QR kod döretmek üçin tekst ýa-da URL giriziň",
        "StatusGeneratingOnInput": "Girizeniňizde döredilýär...",
        "StatusReady": "QR kod taýýar. PNG hökmünde saklap bolýar.",
        "StatusSaved": "Saklandy: {0}",
        "StatusSaveFailed": "Faýl saklanmady",
        "StatusGenerationFailed": "Döretmek ýalňyşlygy",
        "StatusDataTooLong": "Tekst QR kod üçin gaty uzyn. Giriziňizi gysgartyň.",
        "PlaceholderTitle": "QR kod şu ýerde peýda bolar",
        "PlaceholderSubtitle": "Çep tarapda tekst girizmäge başlaň",
        "LoadingText": "Döredilýär...",
        "GenerateButton": "Döret",
        "SaveButton": "PNG sakla",
        "ClearButton": "Arassala",
        "SaveDialogTitle": "QR kody sakla",
        "SaveDialogFilter": "PNG surat (*.png)|*.png",
        "ErrorTitle": "Ýalňyşlyk",
        "ErrorGenerationMessage": "QR kod döredilmedi:\n{0}",
        "ErrorSaveMessage": "Faýl saklanmady:\n{0}",
        "CharacterCountOne": "nyşan",
        "CharacterCountFew": "nyşan",
        "CharacterCountMany": "nyşan",
        "LanguageLabel": "Dil",
        "AutomationInputTextBox": "Tekst ýa-da baglanyşyk girizmek meýdançasy",
        "AutomationGenerateButton": "QR kod döret",
        "AutomationSaveButton": "QR kody PNG hökmünde sakla",
        "AutomationClearButton": "Girizişi we öňünden görmegi arassala",
        "AutomationQrPreview": "QR kod öňünden görmek",
        "AutomationLanguageSelector": "Dil saýlamak",
    },
    "ro": {
        "WindowTitle": "Generator cod QR",
        "AppTitle": "Generator cod QR",
        "AppSubtitle": "Creați coduri QR din text și linkuri",
        "InputLabel": "Text sau link",
        "InputPlaceholder": "Introduceți text sau URL pentru a genera un cod QR",
        "StatusGeneratingOnInput": "Generare la introducere...",
        "StatusReady": "Codul QR este gata. Puteți salva ca PNG.",
        "StatusSaved": "Salvat: {0}",
        "StatusSaveFailed": "Fișierul nu a putut fi salvat",
        "StatusGenerationFailed": "Eroare de generare",
        "StatusDataTooLong": "Textul este prea lung pentru un cod QR. Scurtați introducerea.",
        "PlaceholderTitle": "Codul QR va apărea aici",
        "PlaceholderSubtitle": "Începeți să introduceți text în stânga",
        "LoadingText": "Generare...",
        "GenerateButton": "Generează",
        "SaveButton": "Salvează PNG",
        "ClearButton": "Șterge",
        "SaveDialogTitle": "Salvează codul QR",
        "SaveDialogFilter": "Imagine PNG (*.png)|*.png",
        "ErrorTitle": "Eroare",
        "ErrorGenerationMessage": "Codul QR nu a putut fi creat:\n{0}",
        "ErrorSaveMessage": "Fișierul nu a putut fi salvat:\n{0}",
        "CharacterCountOne": "caracter",
        "CharacterCountFew": "caractere",
        "CharacterCountMany": "caractere",
        "LanguageLabel": "Limbă",
        "AutomationInputTextBox": "Câmp de introducere text sau link",
        "AutomationGenerateButton": "Generează cod QR",
        "AutomationSaveButton": "Salvează codul QR ca PNG",
        "AutomationClearButton": "Șterge introducerea și previzualizarea",
        "AutomationQrPreview": "Previzualizare cod QR",
        "AutomationLanguageSelector": "Selector de limbă",
    },
}

def _install_strings(**overrides):
    base = {
        "InstallLabel": "Installation",
        "InstallButton": "Install application",
        "InstallDialogTitle": "Choose installation type",
        "InstallDialogDescription": "Select where to install QR Code Generator. An install.ini file will be created in the target folder.",
        "InstallOptionLocalTitle": "Local (current user)",
        "InstallOptionLocalDescription": "AppData\\Local — for one user, stays on this computer only",
        "InstallOptionRoamingTitle": "Roaming (current user)",
        "InstallOptionRoamingDescription": "AppData\\Roaming — for one user, syncs with the account profile",
        "InstallOptionAllUsersTitle": "All users",
        "InstallOptionAllUsersDescription": "Program Files — for all users on this computer (administrator rights may be required)",
        "InstallDialogConfirm": "Install",
        "InstallDialogCancel": "Cancel",
        "InstallSuccessTitle": "Installed",
        "InstallSuccessMessage": "Application installed to:\n{0}\n\nStart menu shortcut:\n{1}",
        "InstallSuccessWithWarningMessage": "Application installed to:\n{0}\n\nStart menu shortcut:\n{1}\n\nNote: {2}",
        "InstallShortcutWarning": "Files were installed, but the Start menu shortcut could not be created: {0}",
        "InstallFailedTitle": "Installation failed",
        "InstallFailedMessage": "Could not install the application:\n{0}",
        "AutomationInstallButton": "Open installation options",
    }
    base.update(overrides)
    return base


INSTALL_STRINGS = {
    "en": _install_strings(),
    "de": _install_strings(
        InstallButton="Anwendung installieren",
        InstallDialogTitle="Installationstyp wählen",
        InstallDialogDescription="Wählen Sie, wo der QR-Code-Generator installiert werden soll. Eine install.ini wird im Zielordner erstellt.",
        InstallOptionLocalTitle="Local (aktueller Benutzer)",
        InstallOptionLocalDescription="AppData\\Local — für einen Benutzer, nur auf diesem PC",
        InstallOptionRoamingTitle="Roaming (aktueller Benutzer)",
        InstallOptionRoamingDescription="AppData\\Roaming — für einen Benutzer, synchronisiert mit dem Konto",
        InstallOptionAllUsersTitle="Alle Benutzer",
        InstallOptionAllUsersDescription="Program Files — für alle Benutzer (Administratorrechte können erforderlich sein)",
        InstallDialogConfirm="Installieren",
        InstallDialogCancel="Abbrechen",
        InstallSuccessTitle="Installiert",
        InstallSuccessMessage="Anwendung installiert in:\n{0}\n\nStartmenü-Verknüpfung:\n{1}",
    ),
    "ru": _install_strings(
        InstallLabel="Установка",
        InstallButton="Установить программу",
        InstallDialogTitle="Выбор типа установки",
        InstallDialogDescription="Выберите, куда установить QR Code Generator. В папке установки будет создан файл install.ini.",
        InstallOptionLocalTitle="Local (текущий пользователь)",
        InstallOptionLocalDescription="AppData\\Local — для одного пользователя, только на этом компьютере",
        InstallOptionRoamingTitle="Roaming (текущий пользователь)",
        InstallOptionRoamingDescription="AppData\\Roaming — для одного пользователя, синхронизируется с профилем учётной записи",
        InstallOptionAllUsersTitle="Все пользователи",
        InstallOptionAllUsersDescription="Program Files — для всех пользователей компьютера (может потребоваться запуск от администратора)",
        InstallDialogConfirm="Установить",
        InstallDialogCancel="Отмена",
        InstallSuccessTitle="Установлено",
        InstallSuccessMessage="Приложение установлено в:\n{0}\n\nЯрлык в меню «Пуск»:\n{1}",
        InstallSuccessWithWarningMessage="Приложение установлено в:\n{0}\n\nЯрлык в меню «Пуск»:\n{1}\n\nПримечание: {2}",
        InstallShortcutWarning="Файлы установлены, но ярлык в меню «Пуск» создать не удалось: {0}",
        InstallFailedTitle="Ошибка установки",
        InstallFailedMessage="Не удалось установить приложение:\n{0}",
    ),
    "uk": _install_strings(InstallLabel="Встановлення", InstallButton="Встановити програму", InstallDialogTitle="Вибір типу встановлення", InstallDialogConfirm="Встановити", InstallDialogCancel="Скасувати"),
    "be": _install_strings(InstallLabel="Устаноўка", InstallButton="Усталяваць праграму", InstallDialogTitle="Выбар тыпу ўстаноўкі", InstallDialogConfirm="Усталяваць", InstallDialogCancel="Скасаваць"),
    "kk": _install_strings(InstallLabel="Орнату", InstallButton="Бағдарламаны орнату", InstallDialogConfirm="Орнату", InstallDialogCancel="Болдырмау"),
    "uz": _install_strings(InstallLabel="O'rnatish", InstallButton="Dasturni o'rnatish", InstallDialogConfirm="O'rnatish", InstallDialogCancel="Bekor qilish"),
    "hy": _install_strings(InstallLabel="Տեղադրում", InstallButton="Տեղադրել ծրագիրը", InstallDialogConfirm="Տեղադրել", InstallDialogCancel="Չեղարկել"),
    "az": _install_strings(InstallLabel="Quraşdırma", InstallButton="Proqramı quraşdır", InstallDialogConfirm="Quraşdır", InstallDialogCancel="Ləğv et"),
    "ka": _install_strings(InstallLabel="დაყენება", InstallButton="პროგრამის დაყენება", InstallDialogConfirm="დაყენება", InstallDialogCancel="გაუქმება"),
    "ky": _install_strings(InstallLabel="Орнотуу", InstallButton="Программаны орнотуу", InstallDialogConfirm="Орнотуу", InstallDialogCancel="Жокко чыгаруу"),
    "tg": _install_strings(InstallLabel="Насб", InstallButton="Насби барнома", InstallDialogConfirm="Насб кардан", InstallDialogCancel="Бекор кардан"),
    "tk": _install_strings(InstallLabel="Gurnamak", InstallButton="Programmany gurnamak", InstallDialogConfirm="Gurnamak", InstallDialogCancel="Ýatyr"),
    "ro": _install_strings(InstallLabel="Instalare", InstallButton="Instalează aplicația", InstallDialogConfirm="Instalează", InstallDialogCancel="Anulează"),
}


def write_resx(path: Path, strings: dict[str, str]) -> None:
    lines = [HEADER]
    for key, value in strings.items():
        escaped = (
            value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
        lines.append(f'  <data name="{key}" xml:space="preserve">\n')
        lines.append(f"    <value>{escaped}</value>\n")
        lines.append("  </data>\n")
    lines.append("</root>\n")
    path.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    PROPS_DIR.mkdir(parents=True, exist_ok=True)

    for culture, strings in TRANSLATIONS.items():
        merged = {**strings, **INSTALL_STRINGS.get(culture, INSTALL_STRINGS["en"])}
        file_name = "Resources.resx" if culture == "en" else f"Resources.{culture}.resx"
        write_resx(PROPS_DIR / file_name, merged)

    print(f"Generated {len(TRANSLATIONS)} resource files in {PROPS_DIR}")


if __name__ == "__main__":
    main()